title: Daily Writing
description: Daily writing by BH
url: ""
baseurl: ""

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - design
  - scripts
  - tests
  - uploads
  - writing
  - .generated-writing
  - requirements-import.txt
