#!/usr/bin/env python3
"""Convert monthly Google Docs exports into the site's Markdown format."""

from __future__ import annotations

import argparse
import calendar
import re
import sys
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path


SUPPORTED_SUFFIXES = {".md", ".txt", ".docx", ".pdf"}
SOURCE_NAME = re.compile(r"^(\d{4})-(\d{2})\.(md|txt|docx|pdf)$", re.IGNORECASE)
GENERATED_MARKER = "<!-- Generated by scripts/import_writing.py; do not edit. -->"
MARKDOWN_HEADING = re.compile(r"^\s{0,3}#{1,6}\s+(.+?)\s*#*\s*$")
ISO_DATE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})$")
SLASH_DATE = re.compile(r"^(\d{1,2})/(\d{1,2})/(\d{4})$")
MONTH_DATE = re.compile(
    r"^(?:(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),?\s+)?"
    r"([A-Za-z]+)\s+(\d{1,2})(?:st|nd|rd|th)?,?\s+(\d{4})$",
    re.IGNORECASE,
)
MONTH_TITLE = re.compile(r"^[A-Za-z]+\s+\d{4}$")
WEEKDAY = re.compile(
    r"^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)$",
    re.IGNORECASE,
)


class WritingImportError(Exception):
    """Raised when an upload cannot be converted without losing content."""


@dataclass(frozen=True)
class Entry:
    day: date
    paragraphs: tuple[str, ...]


def parse_date_heading(value: str) -> date | None:
    """Parse the supported standalone date-heading formats."""
    text = normalize_heading(value)

    match = ISO_DATE.fullmatch(text)
    if match:
        return _safe_date(*(int(part) for part in match.groups()))

    match = SLASH_DATE.fullmatch(text)
    if match:
        month, day, year = (int(part) for part in match.groups())
        return _safe_date(year, month, day)

    match = MONTH_DATE.fullmatch(text)
    if match:
        month_name, day, year = match.groups()
        try:
            month = datetime.strptime(month_name[:3], "%b").month
        except ValueError:
            return None
        return _safe_date(int(year), month, int(day))

    return None


def looks_like_date_heading(value: str) -> bool:
    text = normalize_heading(value)
    return any(pattern.fullmatch(text) for pattern in (ISO_DATE, SLASH_DATE, MONTH_DATE))


def normalize_heading(value: str) -> str:
    text = value.replace("\u00a0", " ").strip()
    match = MARKDOWN_HEADING.fullmatch(text)
    if match:
        text = match.group(1)
    return " ".join(text.split())


def _safe_date(year: int, month: int, day: int) -> date | None:
    try:
        return date(year, month, day)
    except ValueError:
        return None


def extract_docx(path: Path) -> list[str]:
    try:
        from docx import Document
    except ImportError as exc:  # pragma: no cover - exercised by the deployment environment
        raise WritingImportError(
            "python-docx is not installed; install requirements-import.txt"
        ) from exc

    document = Document(path)
    if document.tables:
        raise WritingImportError(f"{path}: tables are not supported; use ordinary paragraphs")
    if document.inline_shapes:
        raise WritingImportError(f"{path}: images are not supported; remove them before exporting")

    return [paragraph.text.strip() for paragraph in document.paragraphs]


def extract_text_upload(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8-sig").replace("\r\n", "\n").replace("\r", "\n")
    # Google Docs exports Markdown as one hard-break line per paragraph, with a
    # weekday line immediately before each numeric date. Treating non-empty
    # lines as paragraphs preserves that structure and also works for .txt.
    return [line.strip() for line in text.splitlines() if line.strip()]


def extract_pdf(path: Path) -> list[str]:
    try:
        from pypdf import PdfReader
    except ImportError as exc:  # pragma: no cover - exercised by the deployment environment
        raise WritingImportError(
            "pypdf is not installed; install requirements-import.txt"
        ) from exc

    reader = PdfReader(path)
    if reader.is_encrypted:
        raise WritingImportError(f"{path}: password-protected PDFs are not supported")

    lines: list[str] = []
    for page in reader.pages:
        text = page.extract_text()
        if not text or not text.strip():
            raise WritingImportError(
                f"{path}: a page has no extractable text; use a DOCX export instead"
            )
        lines.extend(line.strip() for line in text.splitlines())
    return reflow_pdf_lines(lines)


def reflow_pdf_lines(lines: list[str]) -> list[str]:
    """Join visual PDF line wraps while retaining blank-line paragraph breaks."""
    paragraphs: list[str] = []
    current: list[str] = []

    def flush() -> None:
        if current:
            paragraphs.append(" ".join(current))
            current.clear()

    for raw_line in lines:
        line = " ".join(raw_line.replace("\u00a0", " ").strip().split())
        if not line:
            flush()
        elif looks_like_date_heading(line):
            flush()
            paragraphs.append(line)
        elif MONTH_TITLE.fullmatch(normalize_heading(line)) and not paragraphs and not current:
            paragraphs.append(line)
        else:
            current.append(line)
    flush()
    return paragraphs


def parse_entries(paragraphs: list[str], expected_year: int, expected_month: int) -> list[Entry]:
    entries: list[Entry] = []
    current_day: date | None = None
    current_body: list[str] = []
    preamble: list[str] = []

    def finish_entry() -> None:
        nonlocal current_body
        if current_day is None:
            return
        body = tuple(paragraph for paragraph in current_body if paragraph.strip())
        if not body:
            raise WritingImportError(
                f"{current_day.isoformat()}: entry has no writing beneath its date"
            )
        entries.append(Entry(current_day, body))
        current_body = []

    index = 0
    while index < len(paragraphs):
        paragraph = paragraphs[index]
        text = paragraph.strip()
        index += 1
        if not text:
            continue
        heading_text = normalize_heading(text)
        if WEEKDAY.fullmatch(heading_text):
            next_text = paragraphs[index] if index < len(paragraphs) else ""
            if parse_date_heading(next_text):
                continue
        parsed_day = parse_date_heading(text)
        if parsed_day:
            finish_entry()
            if (parsed_day.year, parsed_day.month) != (expected_year, expected_month):
                raise WritingImportError(
                    f"{parsed_day.isoformat()}: date does not match upload month "
                    f"{expected_year:04d}-{expected_month:02d}"
                )
            current_day = parsed_day
        elif looks_like_date_heading(text):
            raise WritingImportError(f"invalid date heading: {heading_text}")
        elif current_day is None:
            preamble.append(heading_text)
        else:
            current_body.append(text)

    finish_entry()
    if not entries:
        raise WritingImportError("no standalone date headings were found")
    if len(preamble) > 1 or (preamble and not MONTH_TITLE.fullmatch(preamble[0])):
        raise WritingImportError(
            "text before the first date would be lost; keep only an optional 'Month YYYY' title"
        )

    seen: set[date] = set()
    for entry in entries:
        if entry.day in seen:
            raise WritingImportError(f"duplicate date heading: {entry.day.isoformat()}")
        seen.add(entry.day)
    return sorted(entries, key=lambda entry: entry.day, reverse=True)


def render_markdown(entries: list[Entry], year: int, month: int) -> str:
    title = f"{calendar.month_name[month]} {year}"
    sections = [GENERATED_MARKER, f"# {title}"]
    for entry in entries:
        sections.append(
            f"## {entry.day.isoformat()}\n\n" + "\n\n".join(entry.paragraphs)
        )
    return "\n\n".join(sections) + "\n"


def import_uploads(input_dir: Path, output_dir: Path, writing_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    for old_output in output_dir.glob("*.md"):
        if old_output.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            old_output.unlink()
    sources = sorted(
        path
        for path in input_dir.iterdir()
        if path.is_file() and path.suffix.lower() in SUPPORTED_SUFFIXES
    )
    months: dict[str, Path] = {}
    written: list[Path] = []

    for source in sources:
        match = SOURCE_NAME.fullmatch(source.name)
        if not match:
            raise WritingImportError(
                f"{source}: filename must be YYYY-MM.md, YYYY-MM.txt, "
                "YYYY-MM.docx, or YYYY-MM.pdf"
            )
        year, month = int(match.group(1)), int(match.group(2))
        if month not in range(1, 13):
            raise WritingImportError(f"{source}: month must be between 01 and 12")
        month_key = f"{year:04d}-{month:02d}"
        if month_key in months:
            raise WritingImportError(
                f"{source}: {month_key} is already supplied by {months[month_key]}"
            )
        if (writing_dir / f"{month_key}.md").exists():
            raise WritingImportError(
                f"{source}: writing/{month_key}.md already exists; "
                "use either the upload or Markdown, not both"
            )
        months[month_key] = source

        suffix = source.suffix.lower()
        if suffix in {".md", ".txt"}:
            paragraphs = extract_text_upload(source)
        elif suffix == ".docx":
            paragraphs = extract_docx(source)
        else:
            paragraphs = extract_pdf(source)
        entries = parse_entries(paragraphs, year, month)
        destination = output_dir / f"{month_key}.md"
        if destination.exists():
            raise WritingImportError(
                f"{destination}: refusing to overwrite a file not created by this importer"
            )
        destination.write_text(render_markdown(entries, year, month), encoding="utf-8")
        written.append(destination)

    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-dir", type=Path, default=Path("uploads"))
    parser.add_argument("--output-dir", type=Path, default=Path(".generated-writing"))
    parser.add_argument("--writing-dir", type=Path, default=Path("writing"))
    args = parser.parse_args()

    try:
        written = import_uploads(args.input_dir, args.output_dir, args.writing_dir)
    except (WritingImportError, OSError, ValueError) as exc:
        print(f"Writing import failed: {exc}", file=sys.stderr)
        return 1

    if written:
        for path in written:
            print(f"Generated {path}")
    else:
        print(f"No writing uploads found in {args.input_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
